const constants = {
    ADD_DAY:"ADD_DAY",
    REMOVE_DAY:"REMOVE_DAY",
    SET_GOAL:"SET_GOAL",
    ADD_ERROR:"ADD_ERROR",
    CLEAR_ERROR:"CLEAR_ERROR",
    FETCH_RESORT_NAMES:"FETCH_RESORT_NAMES",
    CANSLE_FETCHING:"CANSLE_FETCHING",
    CHANGE_SUGGESTION:"CHANGE_SUGGESTION",
    CLEAR_SURGGESTION:"CLEAR_SURGGESTION"
}
 
export default constants